<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>SystemOneSharp</PackageId>
    <Description>Unofficial .NET client for the System One API, compatible with TypeSafe Jev and Laya servers.</Description>
    <PackageTags>SystemOne;Jev;Laya;HTTP;client</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
