<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\SystemOneSharp.Extensions.AI\SystemOneSharp.Extensions.AI.csproj" />
    <ProjectReference Include="..\SystemOneSharp.Testing\SystemOneSharp.Testing.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
